stages:
  - test
  - build

check:
  stage: test
  image: registry.gitlab.com/docker-base/go/gocheck
  variables:
    APP_ENV: test
  script:
    - /entrypoint.sh

uint test:
  stage: test
  image: registry.gitlab.com/docker-base/go/gotest
  variables:
    APP_ENV: test
  script:
    - /entrypoint.sh

build:
  stage: build
  image: registry.gitlab.com/go-nm/docker/gobuild
  script:
    - /entrypoint.sh
  artifacts:
    paths:
      - bin/
